### ISSUE TITLE
Profile,measurement screen indication of required fields

### ISSUE THREAD

**Issue by shradha-ajency** [ajency/xooma-track-go#102]
1.The required fields are indicated in the wire frame for profile and measurement with red asterisks, these have to be indicated to the user on load itself, so the user knows which fields he has to fill.

2. The message of required field are currently shown in gray font color. Error messages can be differentiated with red font color.

Also when doing the Product setup page, if reminder is ON, then the time to be entered will e indicated as required field.
 
Refer: 
https://docs.google.com/a/ajency.in/document/d/16iI725h1kpuMvULGkf1rSc5wocLc1IVV68MfY_RJsDE/edit

**Comment by amit0773** [comment]
this is done
