### ISSUE TITLE
Updating the measurement of one part clears the other values

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#123]
Updating the measurement of one part clears the measurement values for parts updated earlier.

Steps:
logged in as : shradha@ajency.in
1. Opened the measurement(Height and weighted saved previously) and updated the waist as '28'
2.Logged out ( From xooma and facebook)
3.Logged in and then updated the value of abdomen as 26 and clicked on save

Current behaviour:The value entered for abdomen is shown whereas the value for waist is not shown(is blank)
expected behaviour: The previously saved details must be displayed if not edited.

**Comment by SurekhaRane** [comment]
This bug was arising because of the js used for those popovers. We were using bootstrap popovers

Now we are using tooltip.js and hence the problem is solved.

**Comment by ashika123** [comment]
Tested
