### ISSUE TITLE
Count of the notification is incorrect

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#124]
Count is not shown for the first notification.

Steps: 
1.Go to view notification and click on product 1
2. Click again on 'product 1' to trigger another notification

Current behaviour: Count is shown as '1' when the second notification is triggered.
Expected behaviour: Count has to be 1 for the 1st notification and 2 for the second

**Comment by deepakpd** [comment]
We are no longer using client side local notifications plugin. This issue can be closed.
