### ISSUE TITLE
Incorrect landing page on closing the app after user logs in to facebook

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#141]
steps: 
1. Open the app and click on login with facebook.
2, Enter the  credentials and the profile page will be displayed
3. Close the app, and then reopen

Current behaviour: On reopening the app the user has to click on 'login with facebook' again to view the profile page'
Expected behaviour: Profile screen has to be visible as the user has not logged out.

**Comment by anujkhurana** [comment]
@Ashika: When this bug is fixed can you show it to me before you close it
on github. Thanks.

**Comment by ashika123** [comment]
Okay.

**Comment by deepakpd** [comment]
This is now fixed. Navigation condition for before login and after login was not handled.

**Comment by deepakpd** [comment]
Reverted my fix as Surekha has now handled it for web.
