### ISSUE TITLE
Keyboard for xooma id and phone number should have 'next' instead of 'go'

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#142]
steps:
Click on the xooma id or on the Phone number field.

Current behaviour: The keyboard displays 'go' key
Expected behaviour: 'next' key has to be displayed which moves the cursor to the next field
Device used: Micromax Canvas

![screenshot_2014-12-31-17-48-42](https://cloud.githubusercontent.com/assets/9797052/5587597/8c1683ca-9115-11e4-977f-27237438283d.png)

**Comment by NikhilAjency** [comment]
Not to be done.

**Comment by ashika123** [comment]
Closed as target users wont be using app on micromax device
