### ISSUE TITLE
Measurement screen does not accept values in decimals

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#145]
steps: 
1. Click on the Fields on the measurement screen.
2. Enter values in decimals.
Current behaviour: Error message is thrown while entering decimal values
expected behaviour: Measurement should accept values in decimals.

![screenshot_2014-12-31-18-18-09](https://cloud.githubusercontent.com/assets/9797052/5587725/6cf1b8bc-9119-11e4-88ab-ad64bc6edef7.png)

**Comment by NikhilAjency** [comment]
Issue #145 Fixed.

**Comment by NikhilAjency** [comment]
The input type number doesnot show .(dot) in Samsung Android soft keyborad. So type is changed to tel and also steps='any' is added for input tag.

**Comment by anujkhurana** [comment]
Please do not close this issue. I will like to understand why this was
assigned to the mobile team and not to Surekha.
