### ISSUE TITLE
Distorted view for buttons at the end of the screen

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#151]
The buttons( View home,View Profile,View Notification) are not aligned correctly
Gender: Shown on two different lines
Device used: Micromax Canvas

![screenshot_2015-01-02-09-47-02](https://cloud.githubusercontent.com/assets/9797052/5594288/e4072c32-926a-11e4-8103-c5a00919795c.png)

**Comment by NikhilAjency** [comment]
This buttons are added by me as on starting the app i am not navigated to the login screen.
This buttons are used for temporary navigation.

**Comment by ashika123** [comment]
Closed as target users wont be using app on micromax device
