### ISSUE TITLE
All Fields on the profile screen has to have same dimensions

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#154]
The fields on the profile screen has to have the same dimensions 

![screenshot_2015-01-02-10-45-09](https://cloud.githubusercontent.com/assets/9797052/5594317/9e12cf18-926c-11e4-9ab2-d4fb8bbb318c.png)

**Comment by anujkhurana** [comment]
Please assign to amit not mobile team.

**Comment by ashika123** [comment]
Issue has been assigned to Amit . The label mobile has been added cause this issue was on phone.
