### ISSUE TITLE
Incorrect page displayed when the screen is unlocked

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#155]
If the landing page for the user is the product list screen( i.e the status of the user is measurements updated) and the user goes back to the profile screen to update it then if the device screen is locked, on unlocking the product list page is dispalyed to the user.
Initial Condition: Status of the user is Measurement updated.
Steps:
1.Open the app. Product list screen will be displayed.
2. Go back to the profile screen and lock the device screen
3. Unlock the device screen

Current behaviour; Product list screen is displayed on unlocking.
Expected behaviour:Profile screen has to be displayed.

**Comment by anujkhurana** [comment]
Please assign to Surekha not mobile team.
