### ISSUE TITLE
Text X2O has to be in caps on login page.

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#176]
Spelling error for 'designed' and 'x2o'
The text shown currently on the login page:
''Has been desiged to help you track your personal x2o water consumption''
Expected: Designed has to be spelled correctly.Text X2O has to be in caps

![login text](https://cloud.githubusercontent.com/assets/9797052/5642749/f54a6e56-9674-11e4-9027-db691ee93d90.png)

**Comment by anujkhurana** [comment]
Screenshot is a must for such bugs.
