### ISSUE TITLE
Button 'login with Facebook' not aligned on Safari

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#178]
Button 'Login with facebook' is not centre aligned on Safari browser(Safari 5.1.7)

Expected Behaviour: The button login with facebook has to be centre aligned as in case of other browsers(Firefox, chrome, IE)

**Comment by anujkhurana** [comment]
We need to test Safari only on a mac. Safari on windows is not supported
any more. Please use Jarryd'a computer for testing on Safari.

Also screenshots for such bugs will help. More the screeshots the better it
is. Please ask @Seonad to show you how she does screenshots and screencasts
for bugs. Use them when you think they will help in understanding the bug.

**Comment by ashika123** [comment]
Okay. Asked Seonad, now using awesome screenshots for taking screenshots.
