### ISSUE TITLE
Multiple 'Authentication cancelled' messages are displayed on Cancelling facebook login box

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#185]
Steps:
1. Click on login with Facebook multiple times hence multiple Facebook login boxes will be displayed.
2. Close the opened Facebook login boxes.

Current behaviour:Multiple 'Authentication cancelled' by user messages are shown
Expected Behaviour: Only one message has to be displayed.

![authentication msg](https://cloud.githubusercontent.com/assets/9797052/5643223/b823912c-967b-11e4-8699-9297d2d44055.png)

**Comment by surajajency** [comment]
Issue confirmed. Can you also provide me with the text to be displayed? or this text is fine?

**Comment by ashika123** [comment]
Keep the text as 'Facebook connect failed.Try again'.
