### ISSUE TITLE
Eastern Time Zone (UTC-05:00) - selected by default

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#186]
steps:
1. Open the profile page and click on the time zone field

Current behaviour: The US time zones are not shown.
Expected Behaviour: The United States uses nine standard time zones. 
Atlantic Time Zone,Eastern Time Zone,Central Time Zone,Mountain Time Zone,Pacific Time Zone
Alaska Time Zone,Hawaii–Aleutian Time Zone,Samoa Time Zone (UTC−11),Chamorro Time Zone (UTC+10)
None of these are shown in the time zone field.

**Comment by shradha-ajency** [comment]
Eastern Time Zone (UTC-05:00) - selected by default
Central Time Zone (UTC-06:00)
Mountain Time Zone (UTC-07:00)
Pacific Time Zone (UTC-08:00)
Alaska Time Zone (UTC-09:00)
Hawaii-Aleutian Time Zone (UTC-10:00)

**Comment by SurekhaRane** [comment]
Need a list of all the possible time zones.

**Comment by ashika123** [comment]
This is done.Default time zone now is America/NewYork

**Comment by anujkhurana** [comment]
Why new york? Where is Xooma worldwide based out of?

**Comment by ashika123** [comment]
Directions to Xooma worldwide on the link http://xooma.com/support pointed to location Hampton
and with refrence to this links kept the default time zone as America/ Newyork
http://www.timetemperature.com/tzva/hampton.shtml
http://www.statoids.com/tus.html
https://www.google.co.in/search?q=Hampton&oq=Hampton&aqs=chrome..69i57.5015j0j7&sourceid=chrome&es_sm=0&ie=UTF-8#q=Hampton+time+zone+
