### ISSUE TITLE
Profile picture and name of the user not required besides the logout button.

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#189]
steps:
1. Click on user name on the header / Click on the profile picture of the user.

Current behaviour: Users profile picture  and name is displayed on the header and then again on the drop down 
Expected Behaviour: Profile picture of the user not required in the drop-down besides logout button.

![logout](https://cloud.githubusercontent.com/assets/9797052/5644744/eeba77e4-968c-11e4-8c42-a4ed6edb7f06.png)

**Comment by amit0773** [comment]
@ashika123  we are changing the ui
