### ISSUE TITLE
Measurements screen should show height in Inches

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#193]
Let the default value for height be 73 inches
Minimum limit 58 inches and maximum limit 108 inches.
![measure_inhes](https://cloud.githubusercontent.com/assets/9797052/5657744/c84c75b6-9719-11e4-8b75-d66f4d3ee0d7.png)

**Comment by anujkhurana** [comment]
Why inches? why not feet?

**Comment by shradha-ajency** [comment]
Zack had mentioned to keep units as inches and pounds, so in the wireframe have added the same units. Also for BMI calculation we have formulas with inches, else we do the conversion(for feet) and use it.
