### ISSUE TITLE
Spacing  between header and text on measurement screen

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#196]
Browser used:Mozilla Firefox 34.0.5
Steps:
1. Open the measurement screen in Firefox

Current behaviour: The spacing shown between the header and the text data on this browser is higher as compared to other browsers.

Expected behaviour: The measurements page has to look same on all the browsers.
![measure_spacing firefox](https://cloud.githubusercontent.com/assets/9797052/5658191/aa64fb04-9723-11e4-94a6-aaa5b68b924c.png)

**Comment by amit0773** [comment]
this is done
