### ISSUE TITLE
Alignment of products on add products screen

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#212]
steps:
1.Click on 'add products' on the my product screen
Current Behaviour:The alignment of the products in the my product screen is improper
Expected Behaviour: Products displayed on this screen has to be aligned.
![addprodcts](https://cloud.githubusercontent.com/assets/9797052/5701377/5e085382-9a70-11e4-9c0f-be111c864335.png)

**Comment by amit0773** [comment]
this is done
