### ISSUE TITLE
Spelling errors on  product setting page

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#215]
![spelling_add product](https://cloud.githubusercontent.com/assets/9797052/5702074/a39b4404-9a7a-11e4-9152-86ae2af5435c.png)

 Choose and consumption spelled incorrectly
Qty has to be spelled completely ie Quantity

**Comment by ashika123** [comment]
![spelling](https://cloud.githubusercontent.com/assets/9797052/5702373/45916b18-9a7f-11e4-9137-befeb31c4bb6.png)

**Comment by SurekhaRane** [comment]
fixed.
