### ISSUE TITLE
Clear button for emaiid field on facebook login box

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#228]
The clear button on email id field on  facebook login box can be only seen on IE 11

Expected Behaviour: The Clear button on email id field has to be visible on all the browsers(Chrome, Mozilla firefox)

![clear_emailid](https://cloud.githubusercontent.com/assets/9797052/5719274/f7e48760-9b3c-11e4-947e-3102da895bd0.png)

**Comment by surajajency** [comment]
invalid issue.
