### ISSUE TITLE
HTML for no access view 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#266]
https://docs.google.com/a/ajency.in/spreadsheets/d/1vmm9psjDbrVb7xZPXCODdAiq30Kn17GQ3-t71EcKXxw/edit#gid=0

![not logged in user tries to view home](https://cloud.githubusercontent.com/assets/9797052/5832043/714a76fa-a164-11e4-8595-a116f4579b8f.png)

**Comment by amit0773** [comment]
this is done
