### ISSUE TITLE
Incorrect position of the label when hovered over gender icon on personal info page

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#282]
Steps:
1. Focus on the Gender icon for 'Male'
2. When the label 'Male' is displayed below the image focus on gender icon for 'female' quickly. 

Current behaviour:When focussed on gender icon for male, the label 'male' is displayed below the icon for Female
expected Behaviour: The label has to be displayed below the icon

![gender label](https://cloud.githubusercontent.com/assets/9797052/5996091/1aa760ca-aac8-11e4-93d8-0fb2687ef5a6.png)

**Comment by amit0773** [comment]
this is done

**Comment by ashika123** [comment]
Tested
