### ISSUE TITLE
Pop up for log out has to disappear when clicked elsewhere 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#283]
Steps:
1.Click on the image for the user in the header
2.Click else where on the screen 
Current behaviour:The pop up is not closed until the user clicks again on the Image 
Expected Behaviour: The pop up has to close when clicked elsewhere on the screen
![log out popup](https://cloud.githubusercontent.com/assets/9797052/5996224/634b61a2-aacb-11e4-864c-e89a6bb01153.png)

**Comment by amit0773** [comment]
@ashika123  this is functionality task
