### ISSUE TITLE
Formatting issues on inventory page

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#295]
Formatting issues on inventory
For inventory-Refill page
![refill formating](https://cloud.githubusercontent.com/assets/9797052/6015908/5d3992f4-aba0-11e4-92f6-a1e3b167ef7d.png)

For inventory- Edit inventory page.
![edit formatting](https://cloud.githubusercontent.com/assets/9797052/6015920/8e05e3d8-aba0-11e4-8045-368d2a17dece.png)

**Comment by amit0773** [comment]
@ashika123 this is functionality task i cant edit
@SurekhaRane  can you fix this its coming thru coffee file

**Comment by ashika123** [comment]
Tested.Fixed
