### ISSUE TITLE
When inventory is refilled updated count is not shown

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#298]
Steps:
1.Open the product inventory, Under refill tab select 'number of new containers'
2.Click on save
3.Go to Edit inventory and refill product
Current behaviour:Number of capsules shown in the two fields do not match,  on refill and edit inventory page as shown in the screenshot
Expected behaviour:The count has to be same on both the fields
![incorret inventory count](https://cloud.githubusercontent.com/assets/9797052/6016345/9f552abc-aba6-11e4-979b-15d81c239e9f.png)

**Comment by SurekhaRane** [comment]
Not a bug.

When we refill the inventory and click on save..a success message is shown and user stays on the same page.
The two values which are shown on  top i.e

How many containers do I have and
How many capsules do i have 

are not reflected on save.

They get reflected when you come back to inventory page.

So...the solution  can be after click on save..redirect the user to 'My Xooma Products'.

**Comment by ashika123** [comment]
Click on save redirects the user to My Xooma Products
