### ISSUE TITLE
'Inventory updated' message on the inventory page incorrectly aligned.

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#299]
The message displayed when the inventory is updated moves to the centre of the page.
Also the alignment of the message has to be corrected
 
![inventory_save](https://cloud.githubusercontent.com/assets/9797052/6017193/6edbc778-abb1-11e4-83b8-5283299ad4de.png)

**Comment by amit0773** [comment]
this is fixed

**Comment by ashika123** [comment]
Tested
