### ISSUE TITLE
The time set for reminders does not match with the time displayed

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#307]
Steps:
1. Go to edit product page
2. set a reminder for a product say at '6 am'

Current behaviour:The time for the reminder displayed on the card is '11 am'
Expected behaviour: The time set should match with that displayed on the card

**Comment by SurekhaRane** [comment]
This was discusses with Shradha.

Times are displayed based on the user's timezone.

**Comment by ashika123** [comment]
This issue is has come up again

**Comment by ashika123** [comment]
Tested
