### ISSUE TITLE
Message on updating measurements and personal info is displayed just once

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#309]
Steps:
1.Go to measurements/personal info screen
2.Update any field and click on save
3. Again update any other field and click on save.
Current behaviour: The message 'Mesurements/ Personal info updated successfully' is displayed only when the user updates the first value
Expected behaviour: Saved successfully has to be displayed every time

**Comment by SurekhaRane** [comment]
This was already discussed....

Messages were put before but styling has been done recntly..and the css applied has to be removed using jquery.

This has not been implemented yet.

**Comment by ashika123** [comment]
Success messages are shown every time after clicking save
