### ISSUE TITLE
Reminder fields are not shown once four or more X2O bottles are selected.

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#312]
If the user selects 4 or more X2O bottles, the remind me fields are not displayed thereafter and  error message is given while adding the product.
steps:
1.Add the product X2O water
2. On the product setting page slide on the slider to select 4 bottles
Current behaviour: The 'fields remind me at' are not displayed
![x2o 4 bottles](https://cloud.githubusercontent.com/assets/9797052/6036345/ceaf37e4-ac69-11e4-8e75-1c3f8885c1d6.png)

**Comment by SurekhaRane** [comment]
Please refer issue number 310.
