### ISSUE TITLE
Tool tips on measurement screen are displayed at incorrect positions on mobile 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#315]
The blinking red spots are positioned out of the human figure
![mesuremnet fig](https://cloud.githubusercontent.com/assets/9797052/6040513/cdb8f710-ac98-11e4-8eb7-9b7d987055c7.png)
Expected:The red blinking spots has to be aligned with the body parts it is meant to indicate

**Comment by amit0773** [comment]
this is done

**Comment by ashika123** [comment]
Verified
