### ISSUE TITLE
Incorrect view when inventory,inventory history and remove product opened in new tab of a browser

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#318]
steps:
1.On the product card click on the options icon and open the links inventory, inventory history and remove product in new tab of a browser- (Right click on each option and select open in new tab)
The following error is thrown
Uncaught TypeError: Cannot read property 'get' of undefined
![inventory_newtab](https://cloud.githubusercontent.com/assets/9797052/6055332/b8155ab8-ad22-11e4-8c99-3e8ad27e54bb.png)

**Comment by SurekhaRane** [comment]
Remove product is an action.It does not have a view associated to it.

**Comment by anujkhurana** [comment]
Can we define the view for remove product then? Not sure I understood. Do
we need to discuss?

**Comment by ashika123** [comment]
Fixed. Remove product being an action now has no option displayed to open in new tab.
