### ISSUE TITLE
When clicked on date picker the keypad and the calender opens up

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#323]
Steps:
1. Open any of the date picker ( On measurement screen/birthdate field on mobile)

Current behaviour: Becomes difficult to enter the date with such behaviour
Expected Behaviour:Only date picker has to be visible
![date picker_key](https://cloud.githubusercontent.com/assets/9797052/6059943/845cb622-ad5d-11e4-805c-2ae264e6df79.png)

**Comment by amit0773** [comment]
this is fixed we have added native datepicker

**Comment by ashika123** [comment]
Verified
