### ISSUE TITLE
Consumption screen for X2O bottle opens if clicked anywhere on the card 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#329]
Steps:
Click anywhere on the card for xooma Bottle
Current Behaviour:
The consumption screen opens when clicked anywhere on xooma bottle
Expected Behaviour:
The consumption screen should open only on clicking within the circle, where the text click to consume is written
![clickable area x2o](https://cloud.githubusercontent.com/assets/9797052/6079602/a7719616-ae2d-11e4-87c8-7d2762ea45b0.png)

**Comment by amit0773** [comment]
@ashika123  This is fixed

**Comment by ashika123** [comment]
Tested. Fixed
