### ISSUE TITLE
Graph is displayed when there is no data available

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#335]
Steps:
1. On the progress chart make a selection such that there is no data available
2.Hover the cursor on the space where graph is displayed

Current behaviour:The message no data available is displayed and also the graph is displayed
expected Behaviour: Graph should not be displayed when there is no data to display
![progresschart_1](https://cloud.githubusercontent.com/assets/9797052/6142982/c9995334-b1e6-11e4-981d-0591d07a52d7.png)

**Comment by SurekhaRane** [comment]
Problem with the chart.js.

Data is not cleared.

Api returns empty response and hence the message is displayed 'No data found'.But when you mouse over js displays the old data.

Solved by hiding the canvas region when the response is empty.

**Comment by ashika123** [comment]
Tested.Fixed
