### ISSUE TITLE
Incorrect unit when the height is displayed on measurement history

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#337]
Steps:
1. From the progress chart options go to measurement history
2.Select any date for which data will be displayed

Current behaviour: The units displayed here are inches 
Expected behaviours: Either units has to be feet or converted value(from feet to inches) has to be displayed
![height_units](https://cloud.githubusercontent.com/assets/9797052/6143485/8affa16a-b1ef-11e4-8a64-fc9bb6c2a2c7.png)

**Comment by SurekhaRane** [comment]
Not a bug.

As per the wireframe.

**Comment by ashika123** [comment]
fixed
