### ISSUE TITLE
Wait cursor for update measurement screen 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#338]
Steps:
1.Go to update measurements
2. Select any date you want to update 

Current behaviour:Difficult to understand the measurement screen transition on  changing the date from the calender
Expected Behaviour: A loader or a wait cursor has to be displayed indicating the screen transitions
![wait cursor](https://cloud.githubusercontent.com/assets/9797052/6143559/e0c227b6-b1f0-11e4-8e22-86ab971b7385.png)

**Comment by SurekhaRane** [comment]
Not a bug.

There is no screen transition.

User just updates the value for a selected date.

Measurement History gives the detailed info for all the dates.

**Comment by ashika123** [comment]
ok
