### ISSUE TITLE
Calender for progress/consumption history needs to be disabled for days prior to user registration

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#341]
Steps:
1. Go to measurement history
2. Select a date prior to user registration 

Current behaviour: User is allowed to view the days prior to his registration on xooma
Expected Behaviour:As updation of consumption and measurement is not allowed for days prior to registration, viewing should also not be allowed
![incoorect message](https://cloud.githubusercontent.com/assets/9797052/6144820/5bb46e74-b201-11e4-8ebe-f92ba1f9daec.png)

**Comment by SurekhaRane** [comment]
A user is allowed to view for all the previous dates.

There is no update on the mentioned screen.

**Comment by ashika123** [comment]
Then change the message on this screen to 'No data available'. since the remaining part will have no meaning when the user selects a date prior to his registration

**Comment by ashika123** [comment]
Tested.Fixed
