### ISSUE TITLE
On consumption history display only the time of consumption

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#343]
Steps:
1. Go to consumption history and click on any date where there is a consumption to display

Current behaviour: Time of consumption is displayed along wit a message few seconds ago
Expected behaviour: Display only the time on the consumption screen
![con_history](https://cloud.githubusercontent.com/assets/9797052/6161704/c3fccc9e-b29a-11e4-8bca-55ecdffda985.png)

**Comment by SurekhaRane** [comment]
Not a bug.

It was done as per the designs.
