### ISSUE TITLE
Time picker gets cut on the consumption screen

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#350]
The time picker gets cut on the consumption screen

![screen cut](https://cloud.githubusercontent.com/assets/9797052/6162272/f4426dfe-b2a5-11e4-9d4f-8da0d852abd5.png)

**Comment by anujkhurana** [comment]
Let's change this to a regular time picker. So let them choose time like a
clock setting and not pre set values. Please discuss if there is confusion
