### ISSUE TITLE
The slider on the measurement should vary from 0-11 for inches

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#368]
Current Behaviour:The variation for the slider for the inches part is from 0-10
Expected Behaviour:The slider on inches should vary from 0-11 and further increase(on 12) should show change in feet part
![measure_inhes](https://cloud.githubusercontent.com/assets/9797052/6223451/dc40a69c-b68f-11e4-862e-1dbd0012cd90.png)

**Comment by SurekhaRane** [comment]
The slider used did not have the option for displaying feet and inches.So it has been replaced with drop downs.
