### ISSUE TITLE
Incorrect display for menu

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#381]
Steps:
1.Keep the home open
2.Click  on the menu and option 'home'(Chose the option to display the already open screen)
Current Behaviour:Incorrect display
![menu](https://cloud.githubusercontent.com/assets/9797052/6262428/c93d314c-b828-11e4-8130-b10f939eace2.png)

**Comment by amit0773** [comment]
this is fixed

**Comment by ashika123** [comment]
Tested
