### ISSUE TITLE
About Xooma should open in device's default browser. FAQ screen is viewed inside app.

### ISSUE THREAD

**Issue by deepakpd** [ajency/xooma-track-go#388]

**Comment by deepakpd** [comment]
This is done.
About Xooma in menu will open link "http://xooma.com/" in device's default browser, i.e outside the app.
FAQ screen is currently displayed inside the app against that of the web which opens FAQ in a new tab.

@ashika123 @shradha-ajency : Please let me know if the current behaviour for FAQ is correct. If we should open FAQ in device browser as that of "About Xooma".

**Comment by ashika123** [comment]
This is fine.
