### ISSUE TITLE
Inappropriate tool tip text for no consumption part of X2O bottle

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#400]
Steps:
1, On the homer page, hover on the non consumed part of the bottle

Current behaviour: The message displayed is '100' always
Expected behaviour: If '0' can be displayed let the message be 'Percentage of bottle 2*consumed:0'
or else 'Percentage of bottle 2* to be consumed: 100'
*=number of the selected bottle.
![no consumption](https://cloud.githubusercontent.com/assets/9797052/6324501/c0045fde-bb60-11e4-9c46-93a19bf7a9a4.png)

**Comment by SurekhaRane** [comment]
As discussed before,the above mentioend tooltips are coming from the js(chart.js) , based on the quantity specified.

If no quantity specified,it doesn't show the circle.

So when there is no consumption value 100 is given.

If not making sense , then we can have a text indicating no consumption along with the quantity(100).

**Comment by ashika123** [comment]
Can the text mentioned in the issue  i.e Percentage of bottle 2 to be consumed: 100 be used?

**Comment by ashika123** [comment]
Testing.
Label changed to 'Pending : 100'
