### ISSUE TITLE
Incorrect menu options are displayed for a new user 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#402]
Steps:
1. Deleted a user from database( User: shradha@ajency.in)
2.Logged in to xooma 

Current behaviour: All the menu options are displayed to the user
Expected behaviour:Menu should have limited options( Home, settings should not be displayed)
![incorrect menu optins](https://cloud.githubusercontent.com/assets/9797052/6326604/5df3fa0c-bb79-11e4-868d-5d0c557c9002.png)

**Comment by SurekhaRane** [comment]
This was handled before.

Issue reported while fixing the problem of menu.
