### ISSUE TITLE
Default time zone is not displayed on firefox

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#403]
Steps:
1. Login to the app for the first time
Current behaviour: The default time zone ' America /New York' is not  displayed
Expected behaviour:The default time zone ' America /New York' has to be displayed
![default _time zone](https://cloud.githubusercontent.com/assets/9797052/6326870/24c924de-bb7c-11e4-91ee-2552dff4515a.png)

**Comment by ashika123** [comment]
Tested

**Comment by SurekhaRane** [comment]
This issue is same as https://github.com/ajency/xooma-track-go/issues/424.
