### ISSUE TITLE
Pressing 'enter' after entering data in the tool tips (Measurements)does not display any change 

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#405]
After entering data on the tool tips in the measurement screen, and then pressing enter( as displayed on the tooltip) does not display any change in the screen for user to understand that the value entered is saved.
Expected:Tool tip should close on pressing enter.

**Comment by amit0773** [comment]
@ashika123  this is done when enter am closing the popbox

**Comment by ashika123** [comment]
Verified
