### ISSUE TITLE
The BMI ratio chart displays graph that coincides with the xaxis

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#410]
Steps:
Go to home page and generate a graph for BMI

Current behaviour: The BMI graph coincides with X axis even when there are measurements updated for a previous day
Expected behaviour: The BMI graph has to be displayed 
![bmi graph](https://cloud.githubusercontent.com/assets/9797052/6343388/c4d4d568-bc0d-11e4-9e7c-b116729a9a5e.png)

**Comment by SurekhaRane** [comment]
This issue is reported because of the css applied for the text 'Normal'.

If hovered on the colored section , it actually shows the points marked.

Css need to be changed.
