### ISSUE TITLE
Normal region is not shown in colour on BMI chart for user prats

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#413]
The normal region for the is displayed in color for user shradha but not for user prats
Also no marking are shown on the graph when the BMi ratio is below normal for any user
![bmi_prats](https://cloud.githubusercontent.com/assets/9797052/6344360/75c72e5c-bc1d-11e4-95fc-9f48c6df3c05.png)

**Comment by SurekhaRane** [comment]
BMI graph is not specific to any user.The behavior is same for all the users.

Also point are always shown when hovered on the BMI section.

There was some problem with the css which Amit has fixed.

**Comment by ashika123** [comment]
verified
