### ISSUE TITLE
Time picker on edit product shows blank values

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#430]
steps:
1.Refresh 'My products'
2.Go to edit product and click on the time pickers.

Current Behaviour:The time picker on one of the field ( out of three reminder fields) shows blank values
![black field](https://cloud.githubusercontent.com/assets/9797052/6411306/2c19cd28-be9d-11e4-8b18-4fdeb24db929.png)

**Comment by SurekhaRane** [comment]
This is not consistent.

Pop up is loaded from the js used.
