### ISSUE TITLE
Inventory history does not show proper data

### ISSUE THREAD

**Issue by shradha-ajency** [ajency/xooma-track-go#433]
Steps:
Go to my products/login shardha@ajency.in/ajency#123
1. Product assimilator has "90" capsules as on 25/02/2015
2.Edited the inventory -> from 90 to 77
3.The available count displays is correct,77 on my product
4.Now click on inventory history, shows as below with no change
![xooma2](https://cloud.githubusercontent.com/assets/8541842/6425473/09c028d6-bf50-11e4-8b5b-8d22e2967706.png)

**Comment by SurekhaRane** [comment]
Not a bug.

The products had 90 capsules on 2015-02-25.

Product was edited today .ie. 2015-02-28.

Clicking on the block for the mentioned date displays the change made for inventory.

It displays samples given to the customer - 13. which gives us the available count equal to 77.

**Comment by shradha-ajency** [comment]
ok. works fine
