### ISSUE TITLE
The default time displayed on the consumption screen gives a error message when selected

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#438]
Steps:
1.To to a consumption screen for any product
2. Click on confirm with the time as the one set by default

Current behaviour:when the default time is selected the message is displayed saying 'Cannot select future time'
Expected: Display the default time in such range that can be selected by the  user.

**Comment by SurekhaRane** [comment]
The time displayed on the time picker pop up is the system time based on the system timezone.

Previously, the time was displayed based on the system timezone and was not taking into consideration app time zone.
So for ex. If we both on app and system it was Asia/Kolkata it showed proper time.But on App we select America/New_York and system timezoen is Asia/Kolkata then time was getting displayed based on the system timezone.(wasn't sure if this was correct).

So changed slightly to consider the app timezone and not the system timezone. 

The time selected on the time picker is compared with the server time.

**Comment by ashika123** [comment]
Verified
