### ISSUE TITLE
The messages on X2O consumption screen needs to be hidden while updating consumption for any other day

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#441]
Steps:
1. Select a past date
2.Update consumption for x2O bottle
Current behaviour: Message is shown to the user with respect to the consumption 
Expected behaviour: The messages has to stay hidden for any other day
![updating x2o consumption](https://cloud.githubusercontent.com/assets/9797052/6457573/b6175d1c-c19d-11e4-937d-24bf9ae202f4.png)

**Comment by SurekhaRane** [comment]
Not a bug.

Solution : We can have generic messages after each consumption.
