### ISSUE TITLE
Emails are not received for user prats

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#443]
No mails are received for user prats 
Last mail received was on feb 19 for this user

**Comment by anujkhurana** [comment]
Is this only for user prats or for all users?

If this is for all users how did you not spot this between 19 feb and now.
For 2 weeks we did not test any functionality on Xooma?

**Comment by ashika123** [comment]
No this is only for user prats. User shradha receives all mails

**Comment by anujkhurana** [comment]
I thought we were going to mute all emails in mandill and only see the
mails in mandrill interface?

Are we sending out emails on the test server using mandrill?

**Comment by SurekhaRane** [comment]
There was some problem with the database tables used for communication module.

It has been fixed now.

Also test mode is enabled for the test server.
