### ISSUE TITLE
Screens in the profile are not displayed to the user on ios

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#448]
Steps:
1.Click on measurements/profile/my products
 Current behaviour:A black screen is shown.
![img_1263](https://cloud.githubusercontent.com/assets/9797052/6553557/ed2abc84-c677-11e4-929a-a56283bd4946.PNG)

**Comment by deepakpd** [comment]
This is fixed.

**Comment by ashika123** [comment]
verified
