### ISSUE TITLE
Set date on home screen can be cleared

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#450]
Steps:
1. Go to home screen, Click today and date picker appears click on clear
 Current behaviour:The date displayed is blank
Expected behaviour: Apply shouldn't be allowed with a blank date
![screenshot_2015-03-10-11-04-49](https://cloud.githubusercontent.com/assets/9797052/6569816/b130104a-c716-11e4-89be-645608103fe9.png)

**Comment by deepakpd** [comment]
This is fixed.
