### ISSUE TITLE
X2O Bottle gets selected when user long presses to consume on ios

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#453]
steps:
1 From the home screen click on the x2o bottle to consume its content
2.On consumption screen long press on the bottle

Current Behaviour: The bottle gets selected 
Expected behaviour:The consumption process should be smooth

![img_1267](https://cloud.githubusercontent.com/assets/9797052/6573105/a58531f4-c73d-11e4-8476-b39b392883c6.PNG)

**Comment by amit0773** [comment]
this is fixed
