### ISSUE TITLE
Backup of all mobile project keys for android and ios

### ISSUE THREAD

**Issue by deepakpd** [ajency/xooma-track-go#465]

**Comment by anujkhurana** [comment]
Can we have a google drive folder where we have all keys for all
ourprojects.

**Comment by deepakpd** [comment]
Yes, there is already a BackUps folder created on google drive by Pratiksha. I have already mailed her all the new keys. Also I have maintained a backup on my personal drive.

@pratsajency : Please delete all the previously stored android keys folder. I have mailed you a zip file containing keys sorted according to projects and play store accounts.
