### ISSUE TITLE
Alert message displayed twice on invalid time

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#80]
steps:
1.Open the app, Click on the Field to enter time 
2.Enter the time lesser then the current time.
3. Click on 'Done'
4. Click 'Ok' when the message is displayed.

Current Behaviour: The alert message 'Select a valid time' is displayed twice.
Expected Behaviour: The message has to be displayed only once.

**Comment by NikhilAjency** [comment]
Not to be done.

**Comment by ashika123** [comment]
Closed as target users wont be using app on micromax device.
