### ISSUE TITLE
Profile: Next ,Prev options in keyboard when user has to enter multiple fields

### ISSUE THREAD

**Issue by shradha-ajency** [ajency/xooma-track-go#88]
1. User on the first field no previous option.
2.User on the last field no next option.
3.Next,Previous options available between them
3.Last field should have done option and perform the function of save*

https://docs.google.com/a/ajency.in/spreadsheets/d/1YdZptaU2CzUjukM7kZ0ceGQQKAoUJErN4wbZNtMSSaM/edit#gid=0

**Comment by NikhilAjency** [comment]
Keyboard Shows go button only for Micromax phone.

**Comment by ashika123** [comment]
Closed as target users wont be using app on micromax device
